version: '3.1'

services:

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  mpbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpbot
    restart: always
    depends_on:
      - selenium
