version: '3.1'

services:

  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444


  mpbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpbot
    restart: always
    links:
      - selenium
    depends_on:
      - selenium
